### ISSUE TITLE
McAfee threat - selenium-manager.exe

### ISSUE THREAD

**Issue by lakto69** [rpakishore/ak_selenium#5]
When I try to run "_chrome = Chrome(headless=False)_" the **McAfee** antivirus identifies the file _"\Lib\site-packages\selenium\webdriver\common\windows\selenium-manager.exe_" as the threat "**_cached<hti>!2c18a3df_**" and does not let me run the script, even after restoring the file.
Is it really a threat?

**Comment by rpakishore** [comment]
I think this is an issue with the selenium base package. See open issue [#14008](https://github.com/SeleniumHQ/selenium/issues/14008) and [#12935](https://github.com/SeleniumHQ/selenium/issues/12935) in selenium package manager.

The gist of the issue is: every-time the `selenium-manager.exe`, it needs to be digitally signed. They are currently working on the issue to streamline this process. 

I wouldn't consider it a threat, and will add the folder as an exclusion from scanning in McAfee. Delete the virtual environment and reinstall.
